# examples/input-sensors.yaml
# IoT sensor data ingestion via CoAP observe
input:
  coap:
    endpoints:
      - "coap://iot-sensor-1:5683"
      - "coap://iot-sensor-2:5683"
      - "coap://iot-gateway:5683"
    observe_paths:
      - "/sensors/temperature"
      - "/sensors/humidity" 
      - "/sensors/+/data"  # Wildcard for multiple sensors
    protocol: "udp"
    connection_pool:
      max_size: 10 # User override (Default: 5)
      idle_timeout: "60s" # User override (Default: "30s")
      health_check_interval: "30s" # User override (Default: "10s")
      # connect_timeout: "10s" # Default
    observer:
      buffer_size: 5000 # User override (Default: 1000)
      observe_timeout: "10m" # User override (Default: "5m")
      # resubscribe_delay: "5s" # Default
    retry_policy:
      max_retries: 5 # User override (Default: 3)
      initial_interval: "2s" # User override (Default: "1s")
      max_interval: "60s" # User override (Default: "30s")
      # multiplier: 2.0 # Default
      # jitter: true # Default
    circuit_breaker:
      enabled: true # Default
      failure_threshold: 3 # User override (Default: 5)
      timeout: "30s" # Default
      # success_threshold: 3 # Default
      # half_open_max_calls: 2 # Default
    # security: # Using defaults (mode: "none")
    # converter: # Using defaults (default_content_format: "application/json", preserve_options: false, etc.)

pipeline:
  processors:
    - mapping: |
        root.device_id = this.metadata.coap_uri_path.split("/")[2]
        root.sensor_type = this.metadata.coap_uri_path.split("/")[1] 
        root.timestamp = now()
        root.data = this.content().parse_json()
        root.metadata = this.metadata.without("coap_options")

output:
  kafka:
    addresses: ["kafka:9092"]
    topic: "iot-sensor-data"
    partition: '${! this.device_id.hash() % 10 }'

---

# examples/output-commands.yaml  
# Send commands to IoT devices via CoAP
input:
  kafka:
    addresses: ["kafka:9092"]
    topics: ["device-commands"]
    consumer_group: "coap-command-sender"

pipeline:
  processors:
    - mapping: |
        meta coap_path = "/actuators/" + this.device_id + "/command"
        meta coap_method = "POST"
        root = this.command_data

output:
  coap:
    endpoints:
      - "coap://device-gateway:5683"
    default_path: "/commands"
    protocol: "udp"
    request_options:
      confirmable: true # Default
      # default_method: "POST" # Default
      timeout: "10s" # User override (Default: "30s")
      content_format: "application/json" # Default
      # auto_detect_format: true # Default
    retry_policy:
      max_retries: 3 # Default
      initial_interval: "1s" # User override (Default: "500ms")
      max_interval: "10s" # Default
      # multiplier: 1.5 # Default
      # jitter: true # Default
    # security: # Using defaults (mode: "none")
    # connection_pool: # Using defaults
    # converter: # Using defaults

---

# examples/secure-dtls.yaml
# Secure CoAP communication with DTLS
input:
  coap:
    endpoints:
      - "coaps://secure-device:5684"
    observe_paths:
      - "/secure/data"
    protocol: "udp-dtls"
    security:
      mode: "psk"
      psk_identity: "client-001"
      psk_key: "${COAP_PSK_KEY}"
    connection_pool:
      max_size: 5 # Default
      # idle_timeout: "30s" # Default
      health_check_interval: "10s" # Default
      # connect_timeout: "10s" # Default
    # observer: # Using defaults
    # retry_policy: # Using defaults
    # circuit_breaker: # Using defaults
    # converter: # Using defaults

output:
  stdout: {}

---

# examples/certificate-auth.yaml
# Certificate-based authentication
input:
  coap:
    endpoints:
      - "coaps://enterprise-device:5684"
    observe_paths:
      - "/enterprise/+/metrics"
    protocol: "tcp-tls"
    security:
      mode: "certificate"
      cert_file: "/etc/ssl/client.crt"
      key_file: "/etc/ssl/client.key"
      ca_cert_file: "/etc/ssl/ca.crt"
      # insecure_skip_verify: false # Default
    observer:
      buffer_size: 10000 # User override (Default: 1000)
      # observe_timeout: "5m" # Default
      # resubscribe_delay: "5s" # Default
    # connection_pool: # Using defaults
    # retry_policy: # Using defaults
    # circuit_breaker: # Using defaults
    # converter: # Using defaults

pipeline:
  processors:
    - mapping: |
        root.enterprise_unit = this.metadata.coap_uri_path.split("/")[2]
        root.metrics = this.content().parse_json()
        root.received_at = now()

output:
  prometheus:
    push_url: "http://pushgateway:9091"
    push_job_name: "coap-metrics"

---

# examples/batch-processing.yaml
# High-throughput batch processing
input:
  coap:
    endpoints:
      - "coap://high-volume-sensor:5683"
    observe_paths:
      - "/stream/data"
    protocol: "tcp"  # TCP for higher throughput
    observer:
      buffer_size: 50000 # User override (Default: 1000)
      # observe_timeout: "5m" # Default
      # resubscribe_delay: "5s" # Default
    converter:
      # default_content_format: "application/json" # Default
      compression_enabled: true # Default
      max_payload_size: 2097152  # 2MB, User override (Default: 1048576)
      # preserve_options: false # Default
    # security: # Using defaults
    # connection_pool: # Using defaults
    # retry_policy: # Using defaults
    # circuit_breaker: # Using defaults

pipeline:
  processors:
    - batch:
        count: 1000
        period: "5s"
    - archive:
        format: "json_array"
    - compress:
        algorithm: "gzip"

output:
  aws_s3:
    bucket: "iot-data-lake"
    path: "coap-data/${! timestamp_unix() }.json.gz"

---

# examples/multi-protocol.yaml
# Mixed protocol usage
input:
  broker:
    inputs:
      - coap:
          endpoints: ["coap://udp-sensors:5683"]
          observe_paths: ["/udp/+/data"]
          protocol: "udp"
      - coap:
          endpoints: ["coap://tcp-devices:5683"]
          observe_paths: ["/tcp/+/events"]
          protocol: "tcp"
      - coap:
          endpoints: ["coaps://secure-gw:5684"]
          observe_paths: ["/secure/+/alerts"]
          protocol: "udp-dtls"
          security:
            mode: "psk"
            psk_identity: "monitor"
            psk_key: "${DTLS_PSK}"

pipeline:
  processors:
    - switch:
        - check: 'this.metadata.coap_uri_path.contains("/alerts")'
          processors:
            - mapping: 'root.priority = "high"'
        - processors:
            - mapping: 'root.priority = "normal"'

output:
  switch:
    cases:
      - check: 'this.priority == "high"'
        output:
          http_client:
            url: "http://alert-manager:9093/api/v1/alerts"
            verb: "POST"
      - output:
          kafka:
            addresses: ["kafka:9092"]
            topic: "coap-events"

---

# examples/debugging.yaml
# Development and debugging configuration
logger:
  level: DEBUG
  format: json

input:
  coap:
    endpoints:
      - "coap://localhost:5683"
    observe_paths:
      - "/debug/test"
    protocol: "udp" # Default
    converter:
      # default_content_format: "application/json" # Default
      # compression_enabled: true # Default
      # max_payload_size: 1048576 # Default (1MB)
      preserve_options: true  # User override (Default: false)
    # security: # Using defaults
    # connection_pool: # Using defaults
    # observer: # Using defaults
    # retry_policy: # Using defaults
    # circuit_breaker: # Using defaults

pipeline:
  processors:
    - log:
        level: INFO
        message: "Received CoAP message: ${! content() }"
    - mapping: |
        root = this
        root.debug_info = {
          "received_at": now(),
          "size_bytes": content().length(),
          "coap_metadata": this.metadata.filter(key -> key.has_prefix("coap_"))
        }

output:
  file:
    path: "/tmp/coap-debug.jsonl"
    codec: "lines"